//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus
    {
        public int bus_id { get; set; }
        public System.TimeSpan bus_time { get; set; }
        public string bus_route { get; set; }
    }
}
